service: aws-serverless-express-valiadmin

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  admin:
    handler: handler.init
    events:
      - http: any /
      - http: any {proxy+}
